pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/jsanthoshkiran/gnitcsedevops.git'
            }
        }
        
        stage('Build') {
            steps {
                script {
                    echo 'Building the project...'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo 'Deploying the project...'
                    // Replace this with your deployment script
                    // e.g., sh 'scp -r . user@server:/var/www/html'
                    sh '''
                        rm -rf *
                        pwd
                        ls -ltr
                        # Define variables
                        #SERVER_USER=user
                        SERVER_IP=localhost
                        WEB_ROOT=/var/www/html

                        # Copy the index.html to the web root directory
                        scp -o StrictHostKeyChecking=no -r UserRegistration/UserRegistraton ${SERVER_IP}:${WEB_ROOT}
                    '''
                }
            }
        }
    }
}
