pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/jsanthoshkiran/gnitcsedevops.git'
            }
        }
        
        stage('Build') {
            steps {
                script {
                    echo 'Building the project...'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the project...'
                    sh '''
                        # Define variables
                        #SERVER_USER=user
                        #SERVER_IP=localhost
                        WEB_ROOT="//E//nginx-1.26.2//html//"

                        # Copy the index.html to the Nginx web root directories
                        cp -o UserReg.html ${WEB_ROOT}
                    '''
            }
        }
    }
}
