pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'mdev', url: 'https://github.com/jsanthoshkiran/gnitcsedevops.git'
            }
        }
        
        stage('Check Current Directory') {

            steps {

                powershell """
                   pwd
                """

            }
        }

        stage('Build') {
            steps {
                script {
                    echo 'Building the project...'
                }
            }
        }

        stage('Deploy to Nginx') {
            steps {
                script {
                    echo 'Deploying the project...'
                    $targetDir = "E:\\nginx-1.26.2\\html"  
                    //sh "robocopy . $targetDir /E"
                    // Use PowerShell to copy files
                    def sourceDir = sh(script: "echo \$(pwd)", returnStdout: true)
                    powershell """
                    Copy-Item -Path "$sourceDir\\*" -Destination "$targetDir" -Recurse -Force  
                    """  
                }  
            }
        }
    }
}
