name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: |
        docker build -t calculator-webapp .
        
    - name: Save Docker image to TAR file
      run: |
        docker save calculator-webapp -o calculator-webapp.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Load Docker image from TAR file
      run: |
        docker load -i calculator-webapp.tar
        
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
